#!/bin/sh

# --------------------------------------
# -- Name : fZf Change directory
# -- Requirement :
# -- * fzf
# -- * zsh
# -- Author : atEaE
# --------------------------------------

function fzfcd() {
	local dir
	dir=$(find ${1:-.} -path '*/\.*' -prune \
					-o -type d -print 2> /dev/null | fzf +m) &&
	cd "$dir"
}

fzfcd