#!/bin/sh

# --------------------------------------
# -- Name : fZf Change directory
# -- Requirement :
# -- * fzf
# -- * zsh
# -- Author : atEaE
# --------------------------------------

ch $(find . -name "*" -type d | fzf)